### PR TITLE
added issue template for TON Test Challenge

### PR DESCRIPTION
**Pull request by Hiyorimi**

### CODE REVIEW

**Review by Raen123 — APPROVED** [review]

**Review by Aleksandr69-max — CHANGES_REQUESTED** [review]
1ab5768ec1753360cd4ce59b9c5bb70a5e82a053

**Comment by Aleksandr69-max** [comment]
> 1ab5768ec1753360cd4ce59b9c5bb70a5e82a053

**Comment by Aleksandr69-max** [comment]
UQCiNWongyVy7dDYp8HQKRJnrc2f6QSd592e8oKVH5FMmZ2u

**Review by Farzadasdianasl — APPROVED** [review]

**Review by Emmydon049 — COMMENTED** [review]
UQC0frez8mjXrGyOriL48AzYgjeoYLHA09nkAWI59howKqpE

**Review by Ve4a — APPROVED** [review]

**Pull request merged**
